defaults: &defaults
  adapter: postgresql
  host:     localhost
  encoding: unicode
  pool: 5
  username:
  password:
  template: template0

development:
  <<: *defaults
  database: taskm_development
production:
  <<: *defaults
  database: taskm_production
test:
  <<: *defaults
  database: taskm_test
